Preserved aspect ratio and added plot_nodes_as_symbols!()
pszufe/OpenStreetMapXPlot.jl pull request #13
Opened 2022-02-07 22:56 UTC by michael-prange

2022-02-08 00:19 UTC, pszufe requested changes
Thank you for this PR!
Could you also try to add one or two tests of the new code to `test/runtests.jl` - this will allow your code to be run and checked for notable errors whenever the project is build. Look for other plotting tests in that file.

2022-02-08 00:19 UTC, pszufe commented on src/plot.jl
> +            # Why doesn't this work?
Please clean the code.
Please provide this as a new implementation of `aspect_ratio` (line 42)
Note that aspect ratio is `w/h`, NOT `h/w` - see https://en.wikipedia.org/wiki/Aspect_ratio_(image)
Hence let's use the correct definition

2022-02-08 00:19 UTC, pszufe commented on src/plot.jl
> +            height = Int(round(aspect_ratio*width))
once we correct `aspect_ratio` to match the actual definition `aspect_ratio*width` will be replaced by `width/aspect_ratio`

2022-02-08 00:19 UTC, pszufe commented on src/plot.jl
> +        end
same correction for other lines

2022-02-08 20:21 UTC, michael-prange commented
No worries. I'll make these changes. 

If I make the changes on my local repository, do I just push them to GitHub? Or do I do yet another pull request?

2022-02-08 20:27 UTC, pszufe commented
> No worries. I'll make these changes.
Thanks!!!
 
> If I make the changes on my local repository, do I just push them to GitHub? Or do I do yet another pull request?
As far as I remember you push then to your repo and they will be automatically seen in this pull request. So no need to create a new one. This makes indeed quite nice workflow.

2022-02-08 20:59 UTC, michael-prange commented
I’ve made all the changes. The Push isn’t working. I get:



When I Fetch the changes, I don’t see any. Then when I attempt another Push, I get the same message. Is there another way for me to do this?

Michael

> On Feb 8, 2022, at 3:27 PM, Przemysław Szufel ***@***.***> wrote:
> 
> 
> No worries. I'll make these changes.
> Thanks!!!
> 
> If I make the changes on my local repository, do I just push them to GitHub? Or do I do yet another pull request?
> As far as I remember you push then to your repo and they will be automatically seen in this pull request. So no need to create a new one. This makes indeed quite nice workflow.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/pszufe/OpenStreetMapXPlot.jl/pull/13#issuecomment-1033031115>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFPBYYWRIP4O7VJJ66R67OTU2F4CLANCNFSM5NYZSCJA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you authored the thread.
>

2022-02-08 22:50 UTC, pszufe commented
Hi,
what message you get when trying to push?

2022-02-09 00:15 UTC, michael-prange commented
![PastedGraphic-1](https://user-images.githubusercontent.com/22944866/153097463-335cec5c-8fc8-4b6c-9482-5711e2edca51.png)

2022-02-09 07:34 UTC, pszufe commented
In order to get the remote changes you use `git pull` not `git fetch`.

I do not know what happened to your repo, but worst case (non expert solution) you can clone it to another directory (from your fork), copy paste the changed files and than push.

2022-02-09 15:02 UTC, michael-prange commented
I deleted my fork and created another one with the changes. I’ve created another pull request that seemed to go without issue.

Michael

> On Feb 9, 2022, at 2:34 AM, Przemysław Szufel ***@***.***> wrote:
> 
> 
> In order to get the remote changes you use git pull not git fetch.
> 
> I do not know what happened to your repo, but worst case (non expert solution) you can clone it to another directory (from your fork), copy paste the changed files and than push.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/pszufe/OpenStreetMapXPlot.jl/pull/13#issuecomment-1033434335>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFPBYYU4C226UPG4IXMR4V3U2IKJNANCNFSM5NYZSCJA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you authored the thread.
>

2022-02-11 13:42 UTC, pszufe commented
I close this one since we merged the other PR

2022-02-11 13:42 UTC, closed without merging